import { Injectable, Logger } from '@nestjs/common';
import { Cron, CronExpression } from '@nestjs/schedule';
import { StatisticService } from '../statistic/statistic.service';
import { InjectRepository } from '@nestjs/typeorm';
import { TaxAndDiscountEntity } from 'src/database/entity/tax-and-discount.entity';
import { Repository } from 'typeorm';

@Injectable()
export class TasksService {
  private readonly logger = new Logger(TasksService.name);

  constructor(
    private statisticService: StatisticService,
    @InjectRepository(TaxAndDiscountEntity)
    private taxDiscountRepository: Repository<TaxAndDiscountEntity>,
  ) {}

  // every week on Monday at 00:10
  @Cron('10 0 * * 1', {
    name: 'weekly-statistics',
    timeZone: 'Asia/Bangkok',
  })
  async handleWeeklyStatistics() {
    this.logger.log('Running weekly statistics auto-generation...');

    try {
      const result = await this.statisticService.autoGenerateWeeklyReport();
      this.logger.log(`Weekly report: ${result.message}`);
    } catch (error) {
      this.logger.error('Failed to generate weekly statistics', error.stack);
    }
  }

  // every month on the 1st day at 00:15
  @Cron('15 0 1 * *', {
    name: 'monthly-statistics',
    timeZone: 'Asia/Bangkok',
  })
  async handleMonthlyStatistics() {
    this.logger.log('Running monthly statistics auto-generation...');

    try {
      const result = await this.statisticService.autoGenerateMonthlyReport();
      this.logger.log(`Monthly report: ${result.message}`);
    } catch (error) {
      this.logger.error('Failed to generate monthly statistics', error.stack);
    }
  }

  // every day at 00:05, update tax/fee/discount status and handle daily statistics
  @Cron('5 0 * * *', {
    name: 'update-tax-discount-status',
    timeZone: 'Asia/Bangkok',
  })
  async handleTaxDiscountStatusUpdate() {
    this.logger.log('Updating tax/discount isActive status...');

    try {
      const now = new Date();

      // Find all taxes/discounts
      const allTaxDiscounts = await this.taxDiscountRepository.find();

      let activatedCount = 0;
      let deactivatedCount = 0;

      for (const taxDiscount of allTaxDiscounts) {
        let shouldBeActive = taxDiscount.isActive;

        if (taxDiscount.applyFrom && taxDiscount.applyFrom > now) {
          shouldBeActive = false; // Not yet started
        }

        if (taxDiscount.applyTo && taxDiscount.applyTo < now) {
          shouldBeActive = false; // Already ended
        }

        if (
          (!taxDiscount.applyFrom || taxDiscount.applyFrom <= now) &&
          (!taxDiscount.applyTo || taxDiscount.applyTo >= now)
        ) {
          // Within valid period - check original isActive value from database
          // If it was manually set to inactive, keep it inactive
          // Only auto-activate if it was previously active
          if (taxDiscount.isActive) {
            shouldBeActive = true;
          }
        }

        // Update if status changed
        if (taxDiscount.isActive !== shouldBeActive) {
          await this.taxDiscountRepository.update(taxDiscount.id, {
            isActive: shouldBeActive,
          });

          if (shouldBeActive) {
            activatedCount++;
            this.logger.log(
              `Activated: ${taxDiscount.name} (${taxDiscount.type})`,
            );
          } else {
            deactivatedCount++;
            this.logger.log(
              `Deactivated: ${taxDiscount.name} (${taxDiscount.type})`,
            );
          }
        }
      }

      this.logger.log(
        `Tax/Discount status update completed: ${activatedCount} activated, ${deactivatedCount} deactivated`,
      );
    } catch (error) {
      this.logger.error('Failed to update tax/discount status', error.stack);
    }
  }

  @Cron('5 0 * * *', {
    name: 'daily-statistics',
    timeZone: 'Asia/Bangkok',
  })
  async handleDailyStatistics() {
    this.logger.log('Running daily statistics auto-generation...');
    try {
      const result = await this.statisticService.autoGenerateDailyReport();
      this.logger.log(`Daily report: ${result.message}`);
    } catch (error) {
      this.logger.error('Failed to generate daily statistics', error.stack);
    }
  }
}
